### PR TITLE
Subtract 1 from submaterial ID

### PR DESCRIPTION
**Pull request by LUModder**
Didn't check if it was subtracting 1 when I first commited it.

### CODE REVIEW

**Comment by suchipi** [comment]
Why even subtract 1 in the first place? Can you elaborate on your reasoning here?

**Comment by LUModder** [comment]
Tables start at 1 while submaterial ID's start at 0

**Comment by thegrb93** [comment]
He doesn't like the garry functions with indexes that start at 0. I don't like them much either, but I don't think you should fight against them like this. It just leads to confusion all around.

**Comment by suchipi** [comment]
To clarify, GetMaterials returns the table indexed starting at 1 and the function that sets the submaterial expects you to start your indices at 0?

**Comment by thegrb93** [comment]
It returns a lua table so yeah.

**Pull request merged**
